[[main]]
    # Top-level menu entry
    identifier = "projets"
    name = "Travaux"
    url = "/projets/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Tout les articles"
    url = "/posts/"
    parent = "blog"
    weight = 2

[[main]]
    identifier = "subsection"
    name = "Sous-sections"
    url = "/subsection/"
    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "blog"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "blog"
    weight = 4

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
    
[[main]]
    identifier = "about"
    name = "A propos de nous"
    url = "/about/"
    weight = 5