[[main]]
    # Top-level menu entry
    identifier = "projets"
    name = "Projets"
    url = "/projets/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "content"
    name = "Plus"
    url = "/posts/"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Tous les articles"
    url = "/posts/"
    parent = "content"
    weight = 2

[[main]]
    identifier = "jeux"
    name = "Nos jeux"
    url = "/jeux/"
    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "content"
    weight = 3

[[main]]
    identifier = "jdb"
    name = "Le lore"
    url = "/posjdbts/"
    parent = "content"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "content"
    weight = 5

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

[[main]]
    identifier = "about"
    name = "Nous"
    url = "/about/"
    weight = 5