### SEO, Analytics & 3rd-party
netlify_forms = true # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
avatar = 'Meridian_Logo_2bis.png' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'Meridian Corp' # Default author for <head> meta
description = "Site de la Meridian Corp." # Add a global meta description to <head>
footer_text = "Crée avec [Hugo Liftoff](https://github.com/wjh18/hugo-liftoff) theme." # Customize footer text
fallback_text = "Il n'y a rien ici, revenez plus tard! " # Fallback text for empty content
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
newsletter_header = "Ma newsletter pour être au courant rapidement"
newsletter_description = "Inscrivez-vous et recevez les nouvelles du blog directement sur votre boite mail !"
newsletter_submit = "Rejoindre"
global_newsletter = false # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors

### Web schemas
# Open Graph
images = ['images/default.png'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "fr_FR" # Open graph locale

# Twitter Cards
twitterSite = "corp_meridian" # Enter your twitter handle without the @
twitterCreator = "corp_meridian" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "Martin Gasque" # Enter your name
schemaLocale = "fr-fr" # Structured data locale
schemaImage = "images/default.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = true
home_hero_socials = false
about_page_socials = true

# Enable or disable individual social icons
[social.links]
  twitter = "corp_meridian"
  # github = "username"
  # stack_overflow = "userid/username" # include user id
  email = "MeridianCorpTV@gmail.com"
  # linkedin = "username" # Comment out to disable
  # mastodon_server = "example.social" # include subdomains if relevant, scheme not needed (defaults to https)
  # mastodon_user = "username" # don't include preceding @

# Enable or disable individual social share icons in posts
[social.share]
  facebook = false
  linkedin = false
  twitter = true
  reddit = false
  email = true