[[main]]
    # Top-level menu entry
    identifier = "projets"
    name = "Project"
    url = "/en/projets/"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "content"
    name = "More"
    url = "/en/posts/"
    weight = 2

[[main]]
    identifier = "posts"
    name = "Redaction"
    url = "/en/posts/"
    parent = "content"
    weight = 2

[[main]]
    identifier = "jeux"
    name = "Our games"
    url = "/en/jeux/"
    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "content"
    weight = 3

[[main]]
    identifier = "jdb"
    name = "The lore"
    url = "/en/jdb/"
    parent = "content"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    parent = "content"
    weight = 5

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/en/contact/"
    weight = 4

[[main]]
    identifier = "about"
    name = "Us"
    url = "/en/about/"
    weight = 5